kind: pipeline
name: default

steps:
  - name: Go test
    image: golang:1.13
    environment:
      GO111MODULE: on
    commands:
      - go mod download
      - go test ./...
    when:
      event:
        - push

  - name: Bump version
    image: quay.io/openware/sdk-tools:0.0.3
    environment:
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile release:push
    when:
      event:
        - push
      branch:
        - master

  - name: Push image
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo: quay.io/openware/postmaster
      registry: quay.io
    when:
      event:
        - push
      branch:
        - master

  - name: "Redeploy on devkube"
    image: rubykube/microkube:0.2.0
    environment:
      WEBHOOK_JWT_SECRET:
        from_secret: devkube_webhook_secret
    commands:
      - export latest_image=quay.io/openware/postmaster:$(cat .tags)
      - cd /home/app
      - bundle exec rake payload:send[postmaster,$latest_image,http://www.devkube.com:1337]
    when:
      event:
        - push
      branch:
        - master

image_pull_secrets:
  - dockerconfigjson
