# Default values for postmaster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: rubykube/postmaster
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

rabbitmq: {}
  host: "rabbitmq.kube-services"
  port: "5672"
  username: "user"
  # password: "changeme"

app:
  vars: {}
    # SENDGRID_API_KEY: "changeme"
    # JWT_PUBLIC_KEY: "changeme"
    # SENDER_EMAIL: "noreply@postmaster.com"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}